{
 "title": "ML Model Performance Monitoring",
 "description": "This dashboard provides an overview of machine learning model performance and experiment tracking.  \nIt visualizes RMSE values for each run, details experiment and run metadata, and highlights the latest model’s RMSE, enabling quick monitoring and comparison of model quality over time.",
 "time": { "from": "2025-05-26T09:03:24.967Z", "to": "2025-05-26T21:03:24.967Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gauge: Latest RMSE",
   "type": "gauge",
   "description": "a gauge view, showing the RMSE value for the latest version of the registered model\n",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  (value->>'rmse')::float AS rmse\r\nFROM evidently_metrics\r\nWHERE value->>'run_id' IS NOT NULL\r\nORDER BY run_time DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Bar Chart: RMSE per Run",
   "type": "barchart",
   "description": "a bar chart, showing the RMSE value for each run. When you hover over a bar, you see the run_uuid, value and name of the run",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  r.run_uuid, \r\n  r.name AS run_name, \r\n  MAX((em.value->>'rmse')::float) AS rmse\r\nFROM runs r\r\nJOIN evidently_metrics em ON r.run_uuid = em.value->>'run_id'\r\nWHERE (em.value->>'rmse') IS NOT NULL\r\nGROUP BY r.run_uuid, r.name"
    }
   ]
  },
  {
   "title": "Table: Experiments and Runs",
   "type": "table",
   "description": "a table view, showing the experiment id, name of the experiment and the name of each run in the experiment, ordered by experiment name",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n  e.experiment_id, \r\n  e.name AS experiment_name, \r\n  r.name AS run_name\r\nFROM experiments e\r\nJOIN runs r ON e.experiment_id = r.experiment_id\r\nORDER BY e.name, r.name"
    }
   ]
  }
 ]
}