version: '3.8'

services:
  postgres:
    build: ./backend-database
    container_name: mlflow_postgres
    env_file:
      - ./backend-database/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mlflow:
    build: ./backend-service-experiment-tracking
    container_name: backend-service-experiment-tracking
    ports:
      - "5000:5000"
    command: >
      mlflow server 
      --backend-store-uri postgresql://postgres:postgres@postgres:5432/mlflow_db 
      --default-artifact-root /mlruns 
      --host 0.0.0.0
    depends_on:
      - postgres
    volumes:
      - ./mlruns:/mlruns

volumes:
  pgdata:
